# Source code for predicting Ames House Prices

In [92]:
# Importing the libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression     #Importing linear regression module
from sklearn.metrics import root_mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
import joblib

In [81]:
# Loading/reading in the data
trainingDF = pd.read_csv(r'../datasets/train.csv')
# trainingDF
testingDF = pd.read_csv(r'../datasets/test.csv')
# testingDF.set_index('Id')
trainingDF

0       False
1       False
2       False
3       False
4       False
        ...
1455    False
1456    False
1457    False
1458    False
1459    False
Name: MSSubClass, Length: 1460, dtype: bool

## Performing data quality checks

In [5]:
# Checking the shape(number of rows and columns) of the data
print('============= Nr. of rows and columns=============')
print(trainingDF.shape)

# Checking the data types
print('==========Data types of the columns=========')
print(trainingDF.dtypes)

# Checking the cardinality of categorical data
print('\n=========Cardinality (Nr. of unique records) of the categorical columns==========')
CategoricalCols = trainingDF.select_dtypes(object)    #Get the columns of categorical data type
for col in list(CategoricalCols.columns):     #Create a list with column names and loop through the list
    print(f'{col}: {CategoricalCols[col].nunique()}')     #Display the unique records in each column
    
# Checking for missing values
print('\n=======Columns with missing values and the number of missing values=========')
MissingValueCols = trainingDF.columns[trainingDF.isna().any()].tolist()     #Get the columns with missing values and convert them to a list
for col in MissingValueCols:
    print(f'{col}: {trainingDF[col].isna().sum()}')

# Checking the formatting of categorical data
print('\n=======Checking the formatting of categorical data(checking for white spaces)=======\n')
for col in list(CategoricalCols.columns):    #checking for extra white spaces
    if (CategoricalCols[col].str.strip() != CategoricalCols[col]).sum() > 0:
        print(f'{col}: {(CategoricalCols[col].str.strip() != CategoricalCols[col]).sum()}')

# Checking the formatting of the numerical data( the Years)
# TODO: Find a way to clean the numerical data(checking the length and removing commas from GarageYrBlt)
# print('\n=============Formatting for the numerical columns=============')
# years = ['YearBuilt','YearRemodAdd','GarageYrBlt','YrSold']
# print(trainingDF[trainingDF['YrSold'].astype(str).str.len() < 2])

# Checking for duplicate records
print('\n=========Number of duplicate records based on Id==========')
DuplicateRecords = trainingDF.duplicated(subset=['Id']).sum()
print(f'Duplicates: {DuplicateRecords}')    #Decided to check based on Id only,since all other rows can repeat

============= Nr. of rows and columns=============
(1460, 81)
==========Data types of the columns=========
Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
                  ...
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 81, dtype: object

=========Cardinality (Nr. of unique records) of the categorical columns==========
MSZoning: 5
Street: 2
Alley: 2
LotShape: 4
LandContour: 4
Utilities: 2
LotConfig: 5
LandSlope: 3
Neighborhood: 25
Condition1: 9
Condition2: 8
BldgType: 5
HouseStyle: 8
RoofStyle: 6
RoofMatl: 8
Exterior1st: 15
Exterior2nd: 16
MasVnrType: 3
ExterQual: 4
ExterCond: 5
Foundation: 6
BsmtQual: 4
BsmtCond: 4
BsmtExposure: 4
BsmtFinType1: 6
BsmtFinType2: 6
Heating: 6
HeatingQC: 5
CentralAir: 2
Electrical: 5
KitchenQual: 4
Functional: 7
FireplaceQu: 5
GarageType: 6
GarageFinish: 3
GarageQual: 5
GarageCond: 5
PavedDrive: 3
PoolQC: 3
Fence: 4
MiscFeature: 4
SaleType: 9
SaleCondition: 6

=======Columns with missing values and the number of missing values=========
LotFrontage: 259
Alley: 1369
MasVnrType: 872
MasVnrArea: 8
BsmtQual: 37
BsmtCond: 37
BsmtExposure: 38
BsmtFinType1: 37
BsmtFinType2: 38
Electrical: 1
FireplaceQu: 690
GarageType: 81
GarageYrBlt: 81
GarageFinish: 81
GarageQual: 81
GarageCond: 81
PoolQC: 1453
Fence: 1179
MiscFeature: 1406

=======Checking the formatting of categorical data(checking for white spaces)=======

Alley: 1369
MasVnrType: 872
BsmtQual: 37
BsmtCond: 37
BsmtExposure: 38
BsmtFinType1: 37
BsmtFinType2: 38
Electrical: 1
FireplaceQu: 690
GarageType: 81
GarageFinish: 81
GarageQual: 81
GarageCond: 81
PoolQC: 1453
Fence: 1179
MiscFeature: 1406

=========Number of duplicate records based on Id==========
Duplicates: 0

## Data Cleaning and Transformation

In [161]:
trainingDFCopy = trainingDF.copy()     #Performing data cleaning on a copy of the original dataset
testingDFCopy = testingDF.copy()  
# Dropping the columns that are not needed
cleanTrainDataDF = (trainingDFCopy.drop(columns=['LotFrontage','LotArea','Alley','LandContour','LotConfig','LandSlope','Neighborhood','Condition1','Condition2',
                                            'BldgType','YearBuilt','YearRemodAdd','RoofMatl','Exterior1st','Exterior2nd','MasVnrType','MasVnrArea','ExterQual',
                                           'BsmtQual','BsmtExposure','BsmtFinType1','BsmtFinSF1','BsmtFinType2','BsmtFinSF2','BsmtUnfSF','TotalBsmtSF','Heating',
                                           'HeatingQC','CentralAir','Electrical','1stFlrSF','2ndFlrSF','LowQualFinSF','GrLivArea','BsmtFullBath','BsmtHalfBath',
                                           'FullBath','HalfBath', 'BedroomAbvGr', 'KitchenAbvGr','KitchenQual','TotRmsAbvGrd','Functional','Fireplaces','FireplaceQu','GarageType',
                                           'GarageYrBlt','GarageFinish','GarageArea','GarageQual','GarageCond','PavedDrive','WoodDeckSF','OpenPorchSF','EnclosedPorch',
                                           '3SsnPorch','ScreenPorch','PoolArea','PoolQC','MiscFeature','MiscVal','MoSold','YrSold']))
cleanTestDataDF = (testingDFCopy.drop(columns=['LotFrontage','LotArea','Alley','LandContour','LotConfig','LandSlope','Neighborhood','Condition1','Condition2',
                                            'BldgType','YearBuilt','YearRemodAdd','RoofMatl','Exterior1st','Exterior2nd','MasVnrType','MasVnrArea','ExterQual',
                                           'BsmtQual','BsmtExposure','BsmtFinType1','BsmtFinSF1','BsmtFinType2','BsmtFinSF2','BsmtUnfSF','TotalBsmtSF','Heating',
                                           'HeatingQC','CentralAir','Electrical','1stFlrSF','2ndFlrSF','LowQualFinSF','GrLivArea','BsmtFullBath','BsmtHalfBath',
                                           'FullBath','HalfBath', 'BedroomAbvGr', 'KitchenAbvGr','KitchenQual','TotRmsAbvGrd','Functional','Fireplaces','FireplaceQu','GarageType',
                                           'GarageYrBlt','GarageFinish','GarageArea','GarageQual','GarageCond','PavedDrive','WoodDeckSF','OpenPorchSF','EnclosedPorch',
                                           '3SsnPorch','ScreenPorch','PoolArea','PoolQC','MiscFeature','MiscVal','MoSold','YrSold']))

# Cleaning the BsmtCond and Fence columns (used 'None' since there can be no basement or fence)
cleanTrainDataDF['BsmtCond'] = cleanTrainDataDF['BsmtCond'].fillna('None')
cleanTrainDataDF['Fence'] = cleanTrainDataDF['Fence'].fillna('None')
# Putting the data in a csv file,which will be used for visualisations
cleanTrainDataDF.to_csv('./cleanTrainData.csv')
# print(cleanTrainDataDF)

cleanTestDataDF['BsmtCond'] = cleanTestDataDF['BsmtCond'].fillna('None')
cleanTestDataDF['Fence'] = cleanTestDataDF['Fence'].fillna('None')
cleanTestDataDF['SaleType'] = cleanTestDataDF['SaleType'].fillna('Oth')
# Rather than dropping the 150 value in MSSubClass since it is not available in the Training Dataset, I decided to replace it with 50 since they're related
cleanTestDataDF['MSSubClass'] = cleanTestDataDF['MSSubClass'].replace(150,50)
# Handling missing values for the MSZoning and Utilities columns in the cleanTestDataDF
mode_value = cleanTestDataDF['Utilities'].mode()[0]  # [0] gets the first mode if multiple
cleanTestDataDF['Utilities'] = cleanTestDataDF['Utilities'].fillna(mode_value)
MSZoningMode_value = cleanTestDataDF['MSZoning'].mode()[0]  # [0] gets the first mode if multiple
cleanTestDataDF['MSZoning'] = cleanTestDataDF['MSZoning'].fillna(MSZoningMode_value)
cleanTestDataDF['GarageCars'] = cleanTestDataDF['GarageCars'].fillna(0.0)
GarageCarsMode = cleanTestDataDF['GarageCars'].mode()[0]  # [0] gets the first mode if multiple
cleanTestDataDF['GarageCars'] = cleanTestDataDF['GarageCars'].replace(5,GarageCarsMode)
cleanTestDataDF['GarageCars'] = cleanTestDataDF['GarageCars'].astype(int)    #Convert the data type of the GarageCars column in Test dataset to be compatible with the Training data set
# print(cleanTestDataDF['MSZoning'].unique())
# Putting the data in a csv file,which will be used for visualisations
cleanTestDataDF.to_csv('./cleanTestData.csv')
# print(cleanTestDataDF)

### Using OneHotEncoding to prepare categorical data for modelling

In [179]:
Encoder = OneHotEncoder(sparse_output =  False)
# OneHotEncoding on the Training Data
TrainOneHotEncoded = Encoder.fit_transform(cleanTrainDataDF[['MSSubClass','MSZoning','Street','LotShape','Utilities','HouseStyle','OverallQual','OverallCond','RoofStyle','ExterCond'
                                ,'Foundation','BsmtCond','GarageCars','Fence','SaleType','SaleCondition']])
TrainOneHotDF = pd.DataFrame(TrainOneHotEncoded, columns = Encoder.get_feature_names_out())
TrainOneHotDF = TrainOneHotDF.drop(columns=['Utilities_NoSeWa','HouseStyle_2.5Fin'])
print(list(TrainOneHotDF.shape))
TrainOneHotDF.to_csv('TrainOneHot.csv')

# OneHotEncoding on the Testing Data
TestOneHotEncoded = Encoder.fit_transform(cleanTestDataDF[['MSSubClass','MSZoning','Street','LotShape','Utilities','HouseStyle','OverallQual','OverallCond','RoofStyle','ExterCond'
                                ,'Foundation','BsmtCond','GarageCars','Fence','SaleType','SaleCondition']])
TestOneHotDF = pd.DataFrame(TestOneHotEncoded, columns = Encoder.get_feature_names_out())
print(list(TestOneHotDF.shape))
TestOneHotDF.to_csv('TestOneHot.csv')

TrainOneHotDF

[1460, 100]
[1459, 100]

,MSSubClass_20,MSSubClass_30,MSSubClass_40,MSSubClass_45,MSSubClass_50,MSSubClass_60,MSSubClass_70,MSSubClass_75,MSSubClass_80,MSSubClass_85,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1456,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1457,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1458,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1459,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

## Feature Engineering and Modeling

In [192]:
# Setting the X and Y variables
X_train,X_valid,Y_train,Y_valid = train_test_split(TrainOneHotDF,trainingDF['SalePrice'],train_size = 0.8,test_size = 0.2, random_state = 0)
# X_train = TrainOneHotDF
X = TestOneHotDF

# Using the LinearRegression algorithm
LR_Model = LinearRegression()
# Fit the model
LR_Model.fit(X_train,Y_train)
LR_y_pred = LR_Model.predict(X_valid)
print(f'LinearRegression: {root_mean_squared_error(Y_valid,LR_y_pred)}')
# Using the RandomForestRegression algorithm
RF_Model = RandomForestRegressor(n_estimators = 10)
RF_Model.fit(X_train,Y_train)
RF_y_pred = RF_Model.predict(X_valid)
print(f'RandomForestRegression: {root_mean_squared_error(Y_valid,RF_y_pred)}')

# Chose LinearRegression as it yields less error
joblib.dump(LR_Model,'AmesHousePricePrediction.pkl')
loadedModel = joblib.load('AmesHousePricePrediction.pkl')     #Loading the model
SalePrice = loadedModel.predict(X).round(2)    #Using the model to make predictions
Id = np.array(testingDF['Id'])
print(len(SalePrice))
print(len(Id))
submissionDict = dict(zip(Id,SalePrice))
submissionDF = pd.DataFrame({
    'Id': Id,
    'SalePrice': SalePrice
})
submissionDF
submissionDF.to_csv('Submission.csv')

LinearRegression: 45882.77374941497
RandomForestRegression: 49277.225942376914
1459
1459

        Id  SalePrice
0     1461  119560.09
1     1462  165638.94
2     1463  166871.32
3     1464  196718.27
4     1465  243447.81
...    ...        ...
1454  2915   82655.34
1455  2916   69125.44
1456  2917  146173.44
1457  2918   94909.20
1458  2919  246661.11

[1459 rows x 2 columns]